import "./globals.css";
import type { Metadata } from "next";
import { Geist, Montserrat } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMontserrat = Montserrat({
  variable: "--font-geist-montserrat",
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <html lang="en" suppressHydrationWarning >
      <body
        suppressHydrationWarning 
        className={`${geistSans.variable} ${geistMontserrat.variable} antialiased`}>
         
        <ThemeProvider
             attribute="class"
             defaultTheme="light"
             enableSystem
             disableTransitionOnChange >
              
              <Navbar />  
             
               {children}
              <Footer />
         </ThemeProvider> 
       
      </body>
    </html>  
   
  );
}
